on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@master
    - name: Setup and Publish
      run: |
        npm install --global --upgrade yarn
        yarn install
        yarn tsc
        yarn npm-cli-login
        npm publish .
